# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://knowpract.github.io/
date_format: "ordinal"
title: 农场悟道
subtitle: "快乐耕耘，知行合一"
description: "yuan的个人博客"
keywords: knowpract, Zhiyuan Chen, yuan
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
port: 4001

# ---------------- #
#      Author      #
# ---------------- #
author: knowpract
organization: alipay
organization_url: https://www.alipay.com/
github_username: knowpract
location: Hangzhou, China
email: yuan_zju@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
    math_engine: mathjax
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: knowpract/knowpract.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: knowpract
#    repo: knowpract.github.io
#    oauth:
#        client_id: 86ae0a07c1215d9751f8
#        client_secret: 6b7ce10b71a8361e66ef998846460112c81ad2f8
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: knowpract
    repo: knowpract.github.io
    clientID: 490e7f1b08ec81ebb251
    clientSecret: 358fca0e5e25a046f6dba2baa1f00077ebf8f66b
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
